version: "3.1"
services:
  mysql:
    image: mysql
    ports: ["3308:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: petstore
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql